// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function animalToString(animal) {
  switch (animal) {
    case 0 : 
        return "dog";
    case 1 : 
        return "cat";
    case 2 : 
        return "octopus";
    
  }
}

function getWelcomeMessage(name, visits, animal) {
  return "Hello " + (name + (", you've visited this website " + (String(visits) + (" times and your favorite animal is the " + animalToString(animal)))));
}

exports.animalToString = animalToString;
exports.getWelcomeMessage = getWelcomeMessage;
/* No side effect */
