// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Gatsby = require("gatsby");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Divider$ReactTemplate = require("./Divider.bs.js");
var Newsletter$ReactTemplate = require("./Newsletter.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Index");

var link = Css.style(/* :: */[
      Css.color(Css.hex("db4d3f")),
      /* :: */[
        Css.textDecoration(Css.none),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* link */link];

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Ian Wilson: JavaScript, ReasonML, and GraphQL"), React.createElement("p", undefined, "I am Ian and I like to code and run, though not simultaneously."), React.createElement("p", undefined, "Sometimes you can find me..."), React.createElement("ul", undefined, React.createElement("li", undefined, "tweeting about web development and tech on twitter ", React.createElement("a", {
                          href: "https://twitter.com/iwilsonq",
                          target: "_blank"
                        }, "@iwilsonq")), React.createElement("li", undefined, "blogging about all stack development on ", React.createElement("a", {
                          href: "https://medium.com/@iwilsonq"
                        }, "Medium"), " or on ", React.createElement("a", {
                          href: "https://dev.to/iwilsonq",
                          target: "_blank"
                        }, "dev.to")), React.createElement("li", undefined, "attempting to record videos on Youtube and Twitch (coming soonish)"), React.createElement("li", undefined, "running about in the hills of the ", React.createElement("a", {
                          href: "https://instagram.com/iwilsonq",
                          target: "_blank"
                        }, "SF Bay Area"))), React.createElement("p", undefined, "Tech note for the curious: this blog is bootstrapped with Gatsby and most of the components are built with ReasonML. The repo exists ", React.createElement("a", {
                      href: "https://github.com/iwilsonq/ianwilson.io_re",
                      target: "_blank"
                    }, "on Github.")), React.createElement("p", undefined, React.createElement("strong", undefined, "Looking to learn more about ReasonML or whatever else I'm working on?"), React.createElement("br", undefined), React.createElement(Gatsby.Link, {
                      to: "/blog",
                      className: link,
                      children: "Definitely check out the blog"
                    })), React.createElement(Divider$ReactTemplate.make, { }), React.createElement(Newsletter$ReactTemplate.make, { }));
}

var make = Index;

var $$default = Index;

exports.str = str;
exports.component = component;
exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
